#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: bwmNGdiskmax
# BEFORE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bwmNGdiskmax"
desc="Vigrid bwmNG monitoring (disk max)"
rcvar="bwmNGdiskmax_enable"

command_path="/Vstorage/GNS3/vigrid/bin"
command="vigrid-bwmng"
command_flags="-F -a start -R /Vstorage -i disk -T max"

start_cmd="bwmNGdiskmax_start"
stop_cmd="bwmNGdiskmax_stop"

bwmNGdiskmax_start()
{
  chk=`ps waxo command | egrep "$command_path/$command $command_flags" | grep -v grep`
  if [ "x$chk" != "x" ]
  then
    echo -n "(already running)"
  else
    $command_path/$command $command_flags || echo -n "($command_path/$command $command_flags) start failed"
  fi
}

bwmNGdiskmax_stop()
{
  # /var/log/bwmNG-disk-max.log -T max
  list=`ps waxo pid,command | egrep "/var/log/bwmNG-disk-max.log -T max" | grep -v grep | awk '{print $1;}'`

  for i in $list
  do
    echo "killing $i..."
    kill $i
  done
}

load_rc_config $name
run_rc_command "$1"