#!/bin/bash
#################################################################################################################################
#
# This material is part of VIGRID extensions to GNS3 for Trainings & CyberRange designs
#
# (c) Laurent LEVIER for script, designs and technical actions, https://github.com/llevier/
# LICENCE: Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA)
#
# Each dependancies (c) to their respective owners
#
#################################################################################################################################

PROJECT_NAME=$1
PROJECT_UUID=$2

PROJECT_START=$3
PROJECT_QUANTITY=$4

PROJECT_TARGET=$5

CONSOLE_RANGE_START=5000
CONSOLE_RANGE_END=10000

if [ "x$PROJECT_NAME" = "x" -o "x$PROJECT_UUID" = "x" -o "x$PROJECT_START" = "x" -o "x$PROJECT_QUANTITY" = "x" -o "x$PROJECT_TARGET" = "x" ]
then
  echo "$0 Source_ProjectName Source_ProjectUUID Target_Starting_project_number Target_Number_of_projects Target_Project_Name"
  exit 1
fi

echo "Console range will be $CONSOLE_RANGE_START-$CONSOLE_RANGE_END"

echo -n "Sanity check: project directory & name..."
CHK="/Vstorage/GNS3/GNS3farm/GNS3/projects/$PROJECT_UUID/$PROJECT_NAME.gns3"
if [ ! -f "$CHK" ]
then
  echo "FAIL to find $CHK, exiting"
  exit 1
fi
echo "OK"

T_QUANTITY_LEN=$((PROJECT_START+PROJECT_QUANTITY))
QUANTITY_LEN=${#T_QUANTITY_LEN}  

COUNT=0
until false
do
  COUNT_CUR=$((PROJECT_START+COUNT))

  printf -v TARGET_PROJECT_NAME "%s%0$QUANTITY_LEN""d" "$PROJECT_TARGET" "$COUNT_CUR"

  echo "Cloning $PROJECT_NAME ($PROJECT_UUID) as $TARGET_PROJECT_NAME..."
  echo -n "  "

  /Vstorage/GNS3/bin/nas-project-lowlevel-clone-ZFS  \
    -G /Vstorage/GNS3/GNS3farm/GNS3 -P /Vstorage/GNS3/GNS3farm/GNS3/projects  \
    -c $CONSOLE_RANGE_START -e $CONSOLE_RANGE_END \
    -Z clone -s $PROJECT_UUID -S $PROJECT_NAME -T $TARGET_PROJECT_NAME
  
  COUNT=$((COUNT+1))
  
  [ $COUNT -ge $PROJECT_QUANTITY ] && break
done

echo "Deployment done, dont forget:"
echo "1- To make gns3:gns3 owner of the project directory on target hosts"
echo "2- To SIGHUP all GNS3 servers..."
